group-it/config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :notes do
      resources :comments
    end
  end
  resources :users, only: [:show, :create, :edit, :update]
  resources :group_members, only: [:new, :create]

  # Sessions and user signup/login:
  root 'sessions#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete 'sessions', to: 'sessions#destroy'

  # get '/groups/:group_id/notes/:note_id/comments/new', to: 'comments#new'
  # get '/groups/:group_id/notes/:id/comments/new', to: 'comments#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

group-it/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

group-it/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  has_one :group_member, through: :note
  has_one :group, through: :note, through: :group_member
  has_one :user, through: :note, through: :group_member
end

group-it/app/models/group.rb
class Group < ApplicationRecord
    has_many :group_members, dependent: :destroy
    has_many :notes, through: :group_members
    has_many :users, through: :group_members

    # validates :title, presence: true, uniqueness: true
    # validates :theme, presence: true
    # validates :description, presence: :true, length: { minimum: 20 }
end

group-it/app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :notes, dependent: :destroy
  has_many :comments, through: :notes

  validates_uniqueness_of :user_id, :scope => [:group_id]

  def my_groups
    self.group
  end

  def my_group_names
    my_groups.title
  end
end

group-it/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :group_member
  has_one :group, through: :group_member
  has_many :comments, dependent: :destroy

  # def groups
  #   self.group_member.map do |group_member|
  #     group_member.group
  #   end
  # end
end

group-it/app/models/user.rb
class User < ApplicationRecord
    has_many :group_members, dependent: :destroy
    has_many :notes, through: :group_members
    has_many :groups, through: :group_members
    has_many :comments, through: :notes, through: :group_members
    
    # validates :username, presence: true, uniqueness: true
end

group-it/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end


  
end

group-it/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @note = Note.find(params[:note_id])
        @comment = Comment.new

    end

    def create
        @comment = Comment.new(comment_params)
        @note = Note.find(params[:note_id].to_i)
        @comment.note_id = @note.id
        @comment.author_id = session[:user_id]
        @comment.save
        redirect_to group_note_path(id: @note.id)
    end

    def index
        @comments = Comment.select {|c| c.note.id == params[:note_id]}
        @note = Note.find(params[:note_id])
    end


private

def comment_params
    params.require(:comment).permit(:content)
end

end

group-it/app/controllers/group_members_controller.rb
class GroupMembersController < ApplicationController

    def new
        @group_member = GroupMember.new
        @group = Group.find(session[:group_id])
        # redirect_to create_group_member_path
    end

    def create
        @group_member = GroupMember.new(user_id: session[:user_id], group_id: session[:group_id])
        
        if @group_member.save
            flash[:notice] = "Successfully joined this group!"
            redirect_to group_path(@group_member.group_id)
        else
            flash[:notice] = "Unable to join group."
            redirect_to groups_path
        end
    end

end

group-it/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

    def index
        @groups = Group.all
    end
    
    def new
        @group = Group.new
    end

    def show
        @group = Group.find(params[:id])
        @notes = @group.notes
        @members = @group.users
        @current_user_member = GroupMember.find_by(user_id: session[:user_id], group_id: @group.id)
    end


    def create
        @group = Group.new(group_params)

        if @group.save
            redirect_to group_path(@group)
        else
            flash[:errors] = @group.errors.full_messages
            redirect_to new_group_path
        end
    end

    def edit
        @group = Group.find(params[:id])
    end

    def update
        @group = Group.find(params[:id])

        if @group.update(group_params)
            redirect_to group_path(@group)
        else
            flash[:errors] = @group.errors.full_messages
            redirect_to edit_group_path
        end
    end

    private

    def group_params
        params.require(:group).permit(:title, :theme, :description)
    end

end

group-it/app/controllers/notes_controller.rb
class NotesController < ApplicationController

    def index
        @current_user = User.find(session[:user_id])
        @current_group = Group.find(params[:group_id])
        # @current_group = Group.first
        # @notes = Note.select{|n| n.group == @current_group}
        @notes = @current_user.notes
    end

    def show
        @note = Note.find(params[:id])
        @comments = @note.comments
        @current_user_member = GroupMember.find_by(user_id: session[:user_id], group_id: params[:group_id])
    end

    def new
        @note = Note.new
    end

    def create
        @note = Note.new(note_params)
        @user_id = session[:user_id]
        @group_members = GroupMember.select{|gm| gm.user_id == @user_id}
        @group_member = @group_members.select{|gm| gm.group_id == params[:group_id].to_i}
        @note.group_member_id = @group_member.first.id
        @note.save
        redirect_to group_note_path(id: @note.id)
    end

    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        @note.update(note_params)
        redirect_to group_note_path(id: params[:id])
    end

    def delete
    end

    private

    def note_params
        params.require(:note).permit(:title, :content)
    end
end

group-it/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(username: params[:username])

        if @user
            session[:user_id] = @user.id
            if Group.first == nil
                session[:group_id] = 1    
            else
                session[:group_id] = Group.first.id
            end
            
            redirect_to user_path(@user)
        else
            flash[:errors] = "Username does not exist, try again"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        session[:group_id] = nil
        redirect_to login_path
    end

end

group-it/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        @groups = @user.groups
        @notes = @user.notes  
    end

    def create
        @user = User.new(params_user)
        if @user.save
            flash[:notice] = "Account successfully created"
            redirect_to login_path
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to signup_path
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if @user.update(params_user)
            redirect_to user_path(@user)    
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to edit_user_path
        end
    end
    private

    def params_user
        params.require(:user).permit(:username, :age, :location, :bio)
    end

end

group-it/app/helpers/application_helper.rb
module ApplicationHelper
end

group-it/app/helpers/comments_helper.rb
module CommentsHelper
end

group-it/app/helpers/group_members_helper.rb
module GroupMembersHelper
end

group-it/app/helpers/groups_helper.rb
module GroupsHelper
end

group-it/app/helpers/notes_helper.rb
module NotesHelper
end

group-it/app/helpers/users_helper.rb
module UsersHelper
end

group-it/app/views/comments/index.html.erb
<h1>All comments RE: <%= @note.title %></h1>


<ol>
<h3>
<% @comments.each do |c| %>
<li><%= c.content %></li>
<% end %>
</h3>
</ol>

group-it/app/views/comments/new.html.erb
<div class="container" style="padding-top: 10px;">
    <div class="text-center px-5">
        <%# <div class="card-columns"> %>
            <div class="card">
                <div class="card-body">
                    <h1>Make a comment RE: <%= @note.title %></h1> <br>

                    <% if flash[:errors] %>
                        <p><%= flash[:errors].count %> error(s)</p>
                        <ul>
                            <% flash[:errors].each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    <% end %>
                    <%= form_with model: @comment, url: group_note_comments_path do |f| %>
                        <h4><%= f.label "Comment: " %></h4>
                        <%= f.text_area :content %><br> <br>
                        <%= f.submit %>
                    <% end %>
                </div>
            </div>
        <%# </div> %>
    </div>
</div>

group-it/app/views/group_members/new.html.erb
<div class="container text-center">
    <div class="text-center px-5">
        <div class="card">
            <div class="card-body">
                <h1>Join Group</h1>
                <h2>To join <%= @group.title %>, click "Join Group"</h2>
                <%= form_for @group_member do |f| %>
                    <%= f.submit "Join Group" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

group-it/app/views/groups/_form.html.erb
<% if flash[:errors] %>
    <p><%= flash[:errors].count %> error(s)</p>
        <ul>
            <% flash[:errors].each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
<% end %>

<%= form_for @group do |f| %>
    <%= f.label "Group Title: " %>
    <%= f.text_field :title %><br>
    <%= f.label "Theme/Subject: " %>
    <%= f.text_field :theme %><br>
    <%= f.label "Description: " %>
    <%= f.text_area :description %><br>
    <%= f.submit %>
<% end %>

group-it/app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form' %>

group-it/app/views/groups/index.html.erb
<div class="text-center">
    <h1 class="display-1" style="font-family: 'Fascinate Inline', cursive; color: #5c98ff;">Group-It Groups</h1>
<hr>
</div>
<style>
    h2 {
        background: #dbdfe5;
    }

    h3 {
        background: lightgrey;
    }
</style>
<div class="container">
<div class="text-center px-5">
    <div class="card-columns">
    <% @groups.each do |group| %>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><%= link_to group.title, group_path(group) %></h4>
                <p class="card-text"><%= group.theme %></p>
                <p class="card-text"><%= pluralize group.users.count, 'User' %></p>
            </div>
        </div>
    <% end %>
    </div>
<!--
<div class="card card-cascade narrower">
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <p>Groups</p>
    </div>
    <div class="px-4">
    <table class= "table table-hover mb-0">
        <thead class="black white-text">
            <tr>
                <th scope="col">Group Name</th>
                <th scope="col">Subject</th>
                <th scope="col"># of Active Users</th>
            </tr>
        </thead>
        <tbody>
            <% @groups.each do |group| %>
                <tr>
                    <td><%= link_to group.title, group_path(group) %></td>
                    <td><%= group.theme %></td>
                    <td><%= pluralize group.users.count, "Users" %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    </div>
</div>
    <div class="container mt-3">
        <% @groups.each do |group| %>
        <div class="row">
            <div class="col-lg-4">
                <div class="demo-content">
                    <h2><%= link_to group.title, group_path(group) %></h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="demo-content">
                    <h3><%= group.theme %></h3>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="demo-content bg-alt">
                    <h3><%= pluralize group.users.count, "User" %></h3>
                </div>
            </div>
        </div>
        <hr>
        <% end %>
    </div> -->
</div>
</div>
<div class="container">
    <div class="text-right" style="padding: 10px;">
        <%= button_to "Create Group", { action: 'new', controller: 'groups' }, {method: 'get', class: 'btn btn-outline-primary btn-lg m-0 waves-effect' } %>
    </div>
</div>

group-it/app/views/groups/new.html.erb
<div class="container" style="padding: 10px;">
    <div class="text-center px-5">
        <div class="card">
            <h1>New Group</h1>

            <%= render 'form' %><br>
        </div>
    </div>
</div>

group-it/app/views/groups/show.html.erb
<div class="text-center">

    <h1 class="display-3" style="font-family: 'Fascinate Inline', cursive; color: #5c98ff;"><%= @group.title %></h1>
    <h3><%= @group.theme %></h3>
    <h3><%= @group.description %></h3>
    <% if @current_user_member %>
        <%= link_to "Create a Note", "/groups/#{@group.id}/notes/new" %>
    <% elsif !session[:user_id] %>
        <%= link_to "Sign In or Sign Up in order to join and begin posting in this group!", login_path %>
    <% else %>
        <% session[:group_id] = @group.id %>
        <%= link_to "Join this group", new_group_member_path %>
    <% end %>
</div>
<div class="text-center">
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-6">
                <h3>This Group's Notes</h3>
                <% @notes.each do |note| %>
                    <h4><%= link_to note.title, "/groups/#{@group.id}/notes/#{note.id}" %></h4>
                <% end %>
            </div>
            <div class="col-md-6">
                <h3>This Group's Members </h3>
                <% @members.each do |member| %>
                    <h4><%= link_to member.username, user_path(member) %></h4>
                <% end %>
            </div>
        </div>
    </div>
</div>

group-it/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Group-It</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Fascinate+Inline&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <style>
        body {
          background: rgb(163,163,163);
          background: linear-gradient(90deg, rgba(163,163,163,1) 0%, rgba(251,242,242,1) 54%, rgba(112,112,112,1) 100%);
          /* background: rgb(255,255,255);
          background: linear-gradient(-95deg, rgba(255,255,255,1) 0%, rgba(203,203,203,1) 100%); */
        }
        li {
          padding-left: 10px;
          padding-right: 10px;
        }
    </style>

  <div class="container">
  <div class="text-center">
    <h1 class="display-6" style="font-family: 'Fascinate Inline', cursive; color: #5c98ff;">Group-It</h1>
  </div>
  <nav class="navbar rounded navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <% if session[:user_id] %>
        <li><%= button_to "My Profile", user_path(current_user), { method: 'get', class: 'btn btn-outline-light btn-sm m-0 waves-effect' } %></li>
       <% end %> 
      <li><%= button_to "Groups", { action: 'index', controller: 'groups' }, {method: 'get', class: 'btn btn-outline-light btn-sm m-0 waves-effect' } %></li>
      <% if session[:group_id] && Group.first %>
        <li><%= button_to "My Notes", group_notes_path(group_id: session[:group_id]), {method: 'get', class: 'btn btn-outline-light btn-sm m-0 waves-effect' } %></li>
      <% end %>
      
    </ul>
    <span class="navbar-text">
      <% if session[:user_id] %>
        <%= link_to "Log Out", '/sessions', method: :delete %>
      <% end %>
    </span>
  </nav>
  </div>
  <!-- <%= button_to "Groups", { action: 'index', controller: 'groups' }, {method: 'get', type: 'button', class: 'btn-floating btn-lg btn-default' } %> -->
    <%= yield %>
  </body>
</html>

group-it/app/views/notes/_form.html.erb
<div>
    <% if flash[:errors] %>
        <p><%= flash[:errors].count %> error(s)</p>
        <ul>
            <% flash[:errors].each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<div>
    <%= form_with model: @note, url: group_notes_path do |f| %>
        <%= f.label "Title: " %>
        <%= f.text_field :title %><br>
        <%= f.label "Content: " %>
        <%= f.text_field :content %><br>
        <%= f.submit %>
    <% end %>
</div>

group-it/app/views/notes/edit.html.erb
<div>
    <h1>Edit your note:</h1>
</div>

<div>
    <% if flash[:errors] %>
        <p><%= flash[:errors].count %> error(s)</p>
        <ul>
            <% flash[:errors].each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<div>
    <%= form_with model: @note, url: group_note_path(id: @note.id) do |f| %>
        <%= f.label "Title: " %>
        <%= f.text_field :title %><br>
        <%= f.label "Content: " %>
        <%= f.text_field :content %><br>
        <%= f.submit %>
    <% end %>
</div>

group-it/app/views/notes/index.html.erb
<div class="container text-center">
    <h2 class="display-6" style="font-family: 'Fascinate Inline', cursive; color: #5c98ff; padding: 10px">All of <%= @current_user.username %>'s notes:</h2>
</div>

<div class="container">
<div class="card card-cascade narrower">
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
    </div>
    <div class="px-4">
    <table class= "table table-hover mb-0">
        <thead class="black white-text">
            <tr>
                <th scope="col">Note Title</th>
                <th scope="col">Note Content</th>
                <th scope="col">Group</th>
            </tr>
        </thead>
        <tbody>
            <% @notes.each do |note| %>
                <tr>
                    <td><%= link_to note.title, group_note_url(id: note.id) %></td>
                    <td><%= note.content %></td>
                    <td><%= link_to note.group.title, group_url(note.group) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    </div>
</div>
</div>

group-it/app/views/notes/new.html.erb
<div class="container" style="padding-top: 10px;">
    <div class="text-center px-5">
        <%# <div class="card-columns"> %>
            <div class="card">
                <div class="card-body">
                    <h1>Make a note:</h1> <br>

                    <% if flash[:errors] %>
                        <p><%= flash[:errors].count %> error(s)</p>
                        <ul>
                            <% flash[:errors].each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    <% end %>
                    <%= form_with model: @note, url: group_notes_path do |f| %>
                        <h4><%= f.label "Title: " %></h4>
                        <%= f.text_field :title %><br>
                        <h4><%= f.label "Content: " %> <br></h4>
                        <div class="form-group">
                            <%= f.text_area :content, id: 'form7', class: 'form-control rounded-0', rows: 7, cols: 5 %><br>
                            <%= f.submit %>
                        </div>
                    <% end %>
                </div>
            </div>
        <%# </div> %>
    </div>
</div>

group-it/app/views/notes/show.html.erb
<div class="container" style="padding-top: 10px;">
    <div class="text-center px-5">
        <%# <div class="card-columns"> %>
            <div class="card">
                <div class="card-body">
                    <h1>Note title: <%= @note.title %></h1>
                    <h3>Content: <%= @note.content %></h3>
                    <div class="container">
                    <ul style="list-style: none">
                    <h4>Comments: </h4>
                    <% @comments.each do |c| %>
                        <li><%= c.content %> <br>
                        <p style="font-size: 12px; padding-left: 50px">-<%= link_to User.find(c.author_id).username, user_path(c.author_id) %> </p></li>
                    <% end %>
                    </ul>
                    <% if @current_user_member %>
                        <%= link_to "New Comment", new_group_note_comment_path(note_id: @note.id) %>
                    <% end %>
                </div>
            </div>
        <%# </div> %>
    </div>
</div>

group-it/app/views/users/_form.html.erb
<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @user do |f| %>
    <%= f.label :username, "Name" %>
    <%= f.text_field :username %>
    <p>This will be your unique username</p> 

    <%= f.label :age, "Age" %>
    <%= f.text_field :age %> <br> <br>
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %> <br><br>

    
        <%= f.label :bio, "Bio" %>
        <%= f.text_area :bio %> <br>
    <%= f.submit %>
    <% end %>
</div>

group-it/app/views/users/edit.html.erb
<div class="container" style="padding: 10px;">
    <div class="text-center px-5">
        <%# <div class="card-columns"> %>
            <div class="card">
                <h1>Edit your GroupIt profile</h1>
                <div class="card-body">
                    <%= render 'form' %>
                </div> 
            </div>
    </div>
</div>

group-it/app/views/users/new.html.erb
<div class="container" style="padding: 10px;">
    <div class="text-center px-5">
        <%# <div class="card-columns"> %>
            <div class="card">
                <h1>Welcome to GroupIt</h1>

                <div>
                    <p>Please fill out your name, age, location, and give us a brief biography of yourself, and make sure to include your interests and any activities you enjoy!</p>
                </div>
                <div class="card-body">
                    <%= render 'form' %>
                </div>
            </div>
    </div>
</div>

group-it/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
  .item1 { grid-area: header; }
  .item2 { grid-area: menu; }
  .item3 { grid-area: main; }
  .item4 { grid-area: right; }
  .item5 { grid-area: footer; }

.grid-container {
  display: grid;
  grid-template-areas:
    'header header header header header header'
    'menu main main main right right'
    'menu footer footer footer footer footer';
  grid-gap: 10px;
  background-color: #2196F3;
  padding: 10px;
}

.grid-container > div {
  background-color: rgba(255, 255, 255, 0.8);
  text-align: center;
  padding: 20px 0;
  font-size: 30px;
}

img {
  width: 90%;
  height: 50%;
}
</style>
</head>
<body>
<div class="container">
</div>

<div class="container" style="padding: 10px;">
    <div class="grid-container">
    <div class="item1">Hello, <%= @user.username %></div>
    <div class="item2">
        <!-- <img src="https://images2.minutemediacdn.com/image/upload/c_fill,g_auto,h_1248,w_2220/f_auto,q_auto,w_1100/v1555921064/shape/mentalfloss/spongebob_0_0.jpg"><br> -->
        Location: <%= @user.location %> <br>
        Age: <%= @user.age %> years old <br>    
        </div>
    <div class="item3">
        Biography <br>
        <%= @user.bio %>
        </div>  
    <div class="item4"> My Groupit Groups <br>
            <% @groups.each do |group| %>
                <h4><%= link_to group.title, group_path(group) %><h4>
            <% end %>
    </div>
    <div class="item5">
        Notes <br><hr>
            <% @notes.each do |note| %>
                <h4>Title: <%= link_to note.title, group_note_path(note) %> <br>
                Group: <%= link_to note.group.title, group_path(note.group) %> </h4><hr>
            <% end %>
    </div>
    </div>
</div>
</body>
</html>








  